### ISSUE TITLE
IOF Email filtering

### ISSUE THREAD

**Issue by ndureiss** [7PH/deadlock.js#38]
Is it possible to introduce an **iof.EmailFilter()** function ?

It doesn't introduce a lot of code to add, possible regex : */^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/* and reduce a lot the code to put into APIDescription :eyes:

**Comment by 7PH** [comment]
Fixed in upstream https://github.com/7PH/io-filter/issues/6

**Comment by 7PH** [comment]
Published: You can use `iof.EmailFilter()` since io-filter@2.1.0
