### ISSUE TITLE
Handle optional parameters

### ISSUE THREAD

**Issue by ndureiss** [7PH/deadlock.js#39]
In my opinion, we should be able to set a parameter as optional when defining an APIDescription route.

**Comment by 7PH** [comment]
Handled in upstream: https://github.com/7PH/io-filter/issues/8

Fixed in io-filter@2.1.0, use the following syntax (`.asOptional()`):
```typescript
new ObjectFilter({
    password: new ValueTypeFilter('string'),
    email: new EmailFilter().asOptional()
})
```
